### ISSUE TITLE
Simulate from any point in the match

### ISSUE THREAD

**Issue by grayskripko** [durtal/servevolleyR#1]

**Comment by durtal** [comment]
Hi @grayskripko 

Did you solve the issue(s)?

I did get your comment via email, I think the functions are flexible enough to simulate a match from any point during a match, though this may need you to write a custom function that uses some of `servevolleyR` functions. Let me know if there's anything I can help with.

Cheers

**Comment by grayskripko** [comment]
no, I did not. It was an error issues. I would like to remove them but it
is possible

**Comment by grayskripko** [comment]
a couple of notes:
1. you use much more loops than needed. It is much slower and much more
useless code lines. R likes vectorisation
https://www.google.ru/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=r+vectorisation&*
2. your core function simPoint can be much shorter with rbinom(p).
Furthermore, it is possible to write with formula p_in * p_1serve  + (1 -
p_in) * p_2serve or something like this in a couple of lines.
3. too much copypastes.

I just noticed.

Cheers

**Comment by grayskripko** [comment]
[image: Inline image 1]

**Comment by durtal** [comment]
Hi @grayskripko 

Much of the package was written over a weekend as I was learning R (I still am tbh), so there are probably many improvements that could be made (especially as it's almost 2years old) but not sure I've the time to address them. Maybe one day 👍
